dist: trusty

language: go

go_import_path: gopkg.in/src-d/go-license-detector.v2
go:
  - 1.11.x
  - 1.12.x

matrix:
  fast_finish: true

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v github.com/haya14busa/goverage

install:
  - export GO111MODULE=on
  - go mod vendor
  - go build -v ./...

script:
  - go vet ./...
  - lint_warns=$(golint ./... | grep -v vendor/) || true
  - if [ ! -z "$lint_warns" ]; then echo "$lint_warns"; exit 1; fi
  - goverage -cpu=1,2 -coverprofile=coverage.txt -covermode=count gopkg.in/src-d/go-license-detector.v2/...
  - sed -i '/assets/d' coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: deploy
      os: osx
      go: 1.12.x
      after_success:
        - gzip -S .darwin_amd64.gz license-detector
      script: skip
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: "license-detector.darwin_amd64.gz"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      os: linux
      go: 1.12.x
      script: skip
      after_success:
        - gzip -S .linux_amd64.gz license-detector
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: "license-detector.linux_amd64.gz"
        skip_cleanup: true
        on:
          tags: true

notifications:
  email: false
